name: Validate Module
on: pull_request

jobs:
  validate:
    name: Validate Terraform Module
    runs-on: ubuntu-20.04
    container:
      image: docker.io/hashicorp/terraform:1.0.3
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - name: Initialize Terraform
      run: terraform init -backend=false
    - name: Validate Terraform Module Syntax
      run: terraform validate
  #security_scanner:
  #  name: Run tfsec Security Scanner
  #  runs-on: ubuntu-20.04
  #  container:
  #    image: docker.io/liamg/tfsec:v0.25.0
  #  steps:
  #  - name: git checkout
  #    uses: actions/checkout@v2
  #  - name: Run security scanner
  #    run: tfsec .
